parameters:
  linestorm.cms.module.page.class:             LineStorm\PageBundle\Module\PageModule

  linestorm.cms.page.routing_loader.class:     LineStorm\PageBundle\Router\PageLoader

  # linestorm.cms.module.page.search_provider.class: LineStorm\PageBundle\Search\PageTriGraphSearchProvider
  # linestorm.cms.module.page.search_provider.class: LineStorm\PageBundle\Search\PageFullTextSearchProvider
  # linestorm.cms.module.page.search_provider.class: LineStorm\PageBundle\Search\PageSolrSearchProvider

services:
  linestorm.cms.module.page:
    class: %linestorm.cms.module.page.class%
    calls:
      - ['setRoutePrefix', [%linestorm.cms.module.page.route_prefix%]]
    tags:
      - { name: linestorm.cms.module }
      - { name: linestorm.content.component_module }


  linestorm.cms.page.routing_loader:
    class: %linestorm.cms.page.routing_loader.class%
    arguments: [@linestorm.cms.model_manager]
    tags:
      - { name: routing.loader }

  #
  # TWIG POST MODULE
  linestorm.cms.twig.module_page_extension:
    class: LineStorm\PageBundle\Twig\PageExtension
    arguments: [ @linestorm.cms.module.page ]
    tags:
      - { name: twig.extension }

  #
  # SEARCH PROVIDERS
#  linestorm.cms.module.post.search_provider:
#    class: %linestorm.cms.module.post.search_provider.class%
#    tags:
#      - { name: linestorm.cms.module.search.provider, map: post }

#  linestorm.cms.module.post.search_provider:
#    class: %linestorm.cms.module.post.search_provider.class%
#    tags:
#      - { name: linestorm.cms.module.search.provider, map: post }
#    calls:
#      - [ 'setSolr', [@solr.client.default]]
